### ISSUE TITLE
Add a Common County/State Metadata source

### ISSUE THREAD

**Issue by ghop02** [covid-projections/covid-data-model#251]
@erccarls has a convenient county level metadata source.  I would like to have common state and county metadata data source (that lives as two files, state and county):

example of the schema:
```
CountyMetadata:
    county: str
    state_alpha_2: str
    state_full: str
    county_fips: str # 3 letter
    state_fips: str # 2 letter
    latitude: float
    longitude: float
    population: int
    population_density: float # whats the units?
    housing_density: float
    age_distribution: List[float]
    age_bin_edges: ???
```

This will help with a couple places where we're relying on odd data sources to get some data sources.
